services:
  php:
    build: .
    container_name: php_todolist
    volumes:
      - .:/var/www/html
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx_todolist
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: